# Kotlin https://kotlinlang.org/docs/gradle.html#setting-kotlin-daemon-s-jvm-arguments
org.gradle.jvmargs=-Xmx8g -Dkotlin.daemon.jvm.options=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseG1GC
kotlin.daemon.jvmargs=-Xmx4g
org.gradle.daemon=true
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
kotlin.code.style=official
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
#Desktop
compose.desktop.packaging.checkJdkVendor=false
github.app.clientId=Iv23li1SBZOzRNTZ2ve9
#Github Env Sync
github.env.sync.token=550c413a3277630b7d3739250c4a7e735475747403621f746e45310b170d315c6860510003276151
github.env.sync.token.key=2d1ec59f-acce-4464-862e-96e9aee684a7
github.env.sync.username=kigya
