services:
  database:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: database
    env_file:
      - docker/${ENV}/env.common
      - docker/${ENV}/env.database
    ports:
      - "8082:8082"
    restart: "no"

  auth:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: auth
    env_file:
      - docker/${ENV}/env.common
      - docker/${ENV}/env.auth
    depends_on:
      - database
    ports:
      - "8081:8081"
    restart: "no"

  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: gateway
    env_file:
      - docker/${ENV}/env.common
      - docker/${ENV}/env.gateway
    depends_on:
      - auth
    ports:
      - "8080:8080"
    restart: "no"
