[versions]
# Basic Environment Setup
googleApiClient = "2.9.0"
hikaricp = "7.0.2"
java = { strictly = "17" }
kgraphqlKtor = "0.40.0"
koinKtor = { strictly = "4.2.0" }
postgresql = "42.7.10"
exposed = { strictly = "1.0.0-rc-4" }

# Kotlin
kotlin = { strictly = "2.3.20" }
kotlinxCoroutines = "1.10.2"

# Serialization
kotlinxSerialization = { require = "1.10.0" }

# DI
koin = { strictly = "4.2.0" }

# Network
ktor = { require = "3.4.1" }

# Detekt
detekt = { require = "1.23.8" }

# Coverage
kover = "0.9.7"

# Server
logback = "1.5.32"

# Jackson
jackson = "2.21.2"

github-env-sync-plugin = "1.0.1"

[libraries]
# Serialization
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
kgraphql-ktor = { module = "de.stuebingerb:kgraphql-ktor", version.ref = "kgraphqlKtor" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koinKtor" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# DI
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Network
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor-serverResources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-clientResources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }

# Detekt Libraries
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Logger
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Exposed
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-date-time = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }

# Gradle Plugins
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

[plugins]
# Plugin Configurations
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

convention-base-microserviceApplication = "base.microserviceApplication:1.0"
convention-base-jvmLibrary = "base.jvmLibrary:1.0"

convention-component-serialization = "component.serialization:1.0"

github-env-sync = { id = "dev.kigya.github-env-sync", version.ref = "github-env-sync-plugin" }
