# detektComposeLopez
Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateParam:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true

# detektComposeKode
compose:
  ReusedModifierInstance:
    active: true
  UnnecessaryEventHandlerParameter:
    active: true
  ComposableEventParameterNaming:
    active: true
  ComposableParametersOrdering:
    active: true
  ModifierHeightWithText:
    active: true
  MissingModifierDefaultValue:
    active: true
  PublicComposablePreview:
    active: true
  TopLevelComposableFunctions:
    active: true
    allowInObjects: false
  ComposableFunctionName:
    active: true
  ConditionCouldBeLifted:
    active: true
    ignoreCallsWithArgumentNames: [ 'modifier', 'contentAlignment' ]
