name: _build-android
on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle (cache)
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x client/gradlew

      - name: Build Android
        working-directory: ./client
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY:  ${{ secrets.GPR_KEY }}
        # Рекомендация 2: Добавлена задача bundleDebug для сборки AAB
        run: ./gradlew :app:headwayAndroid:assembleDebug :app:headwayAndroid:bundleDebug --stacktrace

      - name: Upload APK and AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-build-outputs
          path: |
            client/app/headwayAndroid/build/outputs/apk/**/*.apk
            client/app/headwayAndroid/build/outputs/bundle/**/*.aab
          if-no-files-found: warn
          retention-days: 14
