name: Headway Pipelines

on:
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  issues: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  client:
    name: client
    if: ${{ true }}
    uses: ./.github/workflows/_client.yml
    secrets: inherit
  server:
    name: server
    if: ${{ true }}
    uses: ./.github/workflows/_server.yml
    secrets: inherit
