name: Build (KMP targets)

on:
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    if: ${{ true }}
    uses: ./.github/workflows/_build-android.yml
  desktop:
    if: ${{ false }}
    uses: ./.github/workflows/_build-desktop.yml
  web:
    if: ${{ false }}
    uses: ./.github/workflows/_build-web.yml
  ios:
    if: ${{ false }}
    uses: ./.github/workflows/_build-ios.yml
